const structureDescription = [[
  "Adamantine",
  "Aerial",
  "Amphibious",
  "Ancient",
  "Arachnid",
  "Astrological",
  "Asymmetrical",
  "Bizarre",
  "Black",
  "Bleak",
  "Blue",
  "Bronze",
  "Buried",
  "Celestial",
  "Circuitous",
  "Circular",
  "Clay",
  "Coiled",
  "Collapsing",
  "Concealed",
  "Contaminated",
  "Convoluted",
  "Corroded",
  "Criminal",
  "Crimson",
  "Crooked",
  "Crude",
  "Crumbling",
  "Crystalline",
  "Curious",
  "Cursed",
  "Cyclopean",
  "Decaying",
  "Deceptive",
  "Decomposing",
  "Defiled",
  "Demolished",
  "Demonic",
  "Desolate",
  "Destroyed",
  "Devious",
  "Diamon",
  "Dilapidated",
  "Disorienting",
  "Divided",
  "Dorment",
  "Double",
  "Dream -",
  "Earthen",
  "Ebony",
  "Eldritch",
  "Elliptical",
  "Enchanted",
  "Enclosed",
  "Entombed",
  "Eroding",
  "Ethereal",
  "Fertile",
  "Fortified",
  "Fortress -",
  "Glittering",
  "Grey",
  "Hidden ",
  "High",
  "Invulnerable",
  "Isolated",
  "Labyrinthine",
  "Living",
  "Moaning",
  "Mud -",
  "Octagonal",
  "Painted ",
  "Pearly",
  "Pod -",
  "Poisoned",
  "Quaking",
  "Remade",
  "Ruined",
  "Rune -",
  "Sea-swept",
  "Silent",
  "Spiraling",
  "Star -",
  "Storm-tossed",
  "Sub -",
  "Sunken",
  "Tall",
  "Temporal",
  "Three-part",
  "Titanic",
  "Towering",
  "Toxic",
  "Treasure -",
  "Triangular",
  "Unearthed",
  "Unfinished",
  "Unnatural",
  "Urban",
  "Watery",
  "Wooden"
  ], [
    "Airborne ",
    "Aromatic ",
    "Azure ",
    "Belowground ",
    "Black ",
    "Blue ",
    "Bone- ",
    "Breathing ",
    "Brooding ",
    "Bubbling ",
    "Calcified ",
    "Cliff- ",
    "Coastal ",
    "Concealed ",
    "Conquered ",
    "Contemplation- ",
    "Crimson ",
    "Cruel ",
    "Cryptic ",
    "Cunning ",
    "Dank ",
    "Dark ",
    "Deadly ",
    "Deadly ",
    "Death- ",
    "Dimensional ",
    "Diseased ",
    "Drilling ",
    "Emerald ",
    "Erratic ",
    "Fabrication- ",
    "Factory- ",
    "Fear- ",
    "Feeding ",
    "Flesh- ",
    "Fossilized ",
    "Frightful ",
    "Gas- ",
    "Granite ",
    "Green ",
    "Grey ",
    "Harvest- ",
    "Heliotropic ",
    "Hidden ",
    "Horned ",
    "Horrid ",
    "Hunting ",
    "Hydroponic ",
    "Industrial ",
    "Intermittent ",
    "Intriguing ",
    "Inverted ",
    "Lethargy- ",
    "Levitating ",
    "Limestone ",
    "Midnight ",
    "Monastic ",
    "Mosaic ",
    "Mountain ",
    "Murder- ",
    "Nest- ",
    "Obsidian ",
    "Offshore ",
    "Orb- ",
    "Perilous ",
    "Philosophical ",
    "Platform ",
    "Poorly-built ",
    "Pulsing ",
    "Putrid ",
    "Ramshackle ",
    "Red ",
    "Reversible ",
    "Sacrificial ",
    "Sapphire ",
    "Scarlet ",
    "Seaweed- ",
    "Sentient ",
    "Sex- ",
    "Shadow- ",
    "Ship- ",
    "Shunned ",
    "Singular ",
    "Sinister ",
    "Slaying- ",
    "Star- ",
    "Temporary ",
    "Treasure- ",
    "Tumbled ",
    "Twilight ",
    "Unsealed ",
    "Unstable ",
    "Unthinkable ",
    "Vertical ",
    "Vile ",
    "Wailing ",
    "Walled ",
    "Waterborne ",
    "Weird ",
    "White "
  ]];

  const structure = [[
    "Abbey of the ",
    "Aerie of the ",
    "Asylum of the ",
    "Aviary of the ",
    "Barracks of the ",
    "Bastion of the  ",
    "Bazaar of the  ",
    "Bluffs of the ",
    "Brewery of the ",
    "Bridge of the ",
    "Cairn of the ",
    "Canyon of the ",
    "Carnival of the ",
    "Castle of the ",
    "Cathedral of the ",
    "Cellars of the ",
    "Chapel of the",
    "Chapterhouse of the ",
    "Church of the ",
    "City of the ",
    "Cliffs of the ",
    "Cloister of the ",
    "Cocoon of the ",
    "Coliseum of the ",
    "Contrivance of the ",
    "Cottage of the ",
    "Court of the ",
    "Crags of the ",
    "Craters of the ",
    "Crypt of the ",
    "Demi-plane of the ",
    "Dens of the ",
    "Dimension of the ",
    "Domain of the ",
    "Dome of the ",
    "Dungeons of the ",
    "Dwelling of the ",
    "Edifice of the ",
    "Fane of the ",
    "Farm of the ",
    "Forest of the ",
    "Forge of the  ",
    "Fortress of the ",
    "Foundry of the ",
    "Galleon of the ",
    "Galleries of the ",
    "Garden of the ",
    "Garrison of the ",
    "Generator of the ",
    "Glade of the ",
    "Globe of the ",
    "Grotto of the ",
    "Hall of the ",
    "Halls of the ",
    "Harbor of the ",
    "Haven of the ",
    "Hatcheries of the ",
    "Hill of the ",
    "Hive of the ",
    "Holt of the ",
    "House of the ",
    "Hut of the ",
    "Island of the ",
    "Isles of the ",
    "Jungle of the ",
    "Keep of the ",
    "Kennels of the ",
    "Labyrinth of the ",
    "Lair of the ",
    "Lighthouse of the ",
    "Lodgings of the ",
    "Manse of the ",
    "Mansion of the ",
    "Marsh of the ",
    "Maze of the ",
    "Megalith of the ",
    "Mill of the ",
    "Mines of the ",
    "Monastery of the ",
    "Monolith of the ",
    "Mounds of the ",
    "Necropolis of the ",
    "Nest of the ",
    "Obelisk of the ",
    "Outpost of the ",
    "Pagoda of the ",
    "Palace of the ",
    "Pavilion of the ",
    "Pits of the ",
    "Prison of the ",
    "Pyramid of the ",
    "Rift of the ",
    "Sanctuary of the ",
    "Sanctum of the ",
    "Shrine of the ",
    "Spire of the ",
    "Stockades of the ",
    "Stronghold of the ",
    "Tower of the ",
    "Zeppelin of the "
    ], [
      "Abbey of the ",
      "Aerie of the ",
      "Asylum of the ",
      "Aviary of the ",
      "Barracks of the ",
      "Bastion of the ",
      "Bazaar of the ",
      "Bluffs of the ",
      "Bridge of the ",
      "Cairn of the ",
      "Canyon of the ",
      "Carnival of the ",
      "Castle of the ",
      "Cathedral of the ",
      "Cellars of the ",
      "Chapel of the ",
      "Church of the ",
      "City of the ",
      "Cliffs of the ",
      "Cloister of the ",
      "Cocoon of the ",
      "Coliseum of the ",
      "Contrivance of the ",
      "Cottage of the ",
      "Court of the ",
      "Cradle of the ",
      "Crags of the ",
      "Craters of the",
      "Crypt of the ",
      "Dens of the ",
      "Dimension of the ",
      "Domains of the ",
      "Dome of the ",
      "Dungeons of the ",
      "Dwelling of the ",
      "Edifice of the ",
      "Fane of the ",
      "Farm of the ",
      "Forest of the ",
      "Forge of the ",
      "Fortress of the ",
      "Foundry of the ",
      "Galleon of the ",
      "Galleries of the ",
      "Garden of the ",
      "Garrison of the ",
      "Generator of the ",
      "Glade of the ",
      "Globe of the ",
      "Grotto of the ",
      "Hall of the ",
      "Halls of the ",
      "Harbor of the ",
      "Hatcheries of the ",
      "Haven of the ",
      "Hill of the ",
      "Hive of the ",
      "Holt of the ",
      "House of the ",
      "Hut of the ",
      "Island of the ",
      "Isles of the ",
      "Jungle of the ",
      "Keep of the ",
      "Kennels of the ",
      "Labyrinth of the ",
      "Lair of the ",
      "Lighthouse of the ",
      "Lodgings of the ",
      "Manse of the ",
      "Mansion of the ",
      "Marsh of the ",
      "Maze of the ",
      "Megalith of the ",
      "Mill of the ",
      "Mines of the ",
      "Monastery of the ",
      "Monolith of the ",
      "Mounds of the ",
      "Necropolis of the ",
      "Nest of the ",
      "Obelisk of the ",
      "Outpost of the ",
      "Pagoda of the ",
      "Palace of the ",
      "Pavilion of the ",
      "Pits of the ",
      "Plane of the ",
      "Prison of the ",
      "Pyramid of the ",
      "Rift of the ",
      "Sanctuary of the ",
      "Sanctum of the ",
      "Shrine of the ",
      "Spire of the ",
      "Stockades of the ",
      "Stronghold of the ",
      "Tower of the ",
      "Webs of the ",
      "Zeppelin of the "
    ]];

    const firstFeature = [[
      "Ant- ",
      "Ape- ",
      "Baboon- ",
      "Bat- ",
      "Beetle- ",
      "Bitter ",
      "Blood ",
      "Bone- ",
      "Brain ",
      "Broken ",
      "Bronze ",
      "Burned ",
      "Cabalistic ",
      "Carnal ",
      "Caterpillar- ",
      "Centipede- ",
      "Changing ",
      "Chaos- ",
      "Cloud- ",
      "Cockroach- ",
      "Crimson ",
      "Crippled ",
      "Crocodile- ",
      "Dark ",
      "Death- ",
      "Decayed ",
      "Deceitful ",
      "Deluded ",
      "Dinosaur- ",
      "Diseased ",
      "Dragonfly- ",
      "Dread ",
      "Elemental ",
      "Elephant- ",
      "Feathered ",
      "Fiery ",
      "Flame ",
      "Flying ",
      "Ghostly ",
      "Gluttonous ",
      "Gnarled ",
      "Half-breed ",
      "Heart- ",
      "Hive ",
      "Hollow ",
      "Horned ",
      "Howling ",
      "Hunchback ",
      "Hyena- ",
      "Ice ",
      "Immoral ",
      "Immortal ",
      "Imprisoned ",
      "Insane ",
      "Insatiable ",
      "Iron ",
      "Jackal- ",
      "Jade ",
      "Jewel ",
      "Leech- ",
      "Legendary ",
      "Leopard- ",
      "Lesser ",
      "Lion- ",
      "Loathsome ",
      "Lunar ",
      "Mad ",
      "Mammoth- ",
      "Man-eating ",
      "Mantis- ",
      "Many-legged ",
      "Mist- ",
      "Monkey- ",
      "Moth- ",
      "Mutant ",
      "Ooze ",
      "Outlawed ",
      "Polluted ",
      "Rat- ",
      "Reawakened ",
      "Resurrected ",
      "Sabertooth ",
      "Scarlet ",
      "Scorched ",
      "Secret ",
      "Shadow ",
      "Shattered ",
      "Skeletal ",
      "Slave ",
      "Slime- ",
      "Slug- ",
      "Snail- ",
      "Snake- ",
      "Twisted ",
      "Undead ",
      "Unholy ",
      "Unseen ",
      "Wasp- ",
      "Worm- ",
      "Zombie "
      ], [
        "Ant- ",
        "Armored ",
        "Army of the ",
        "Artificial ",
        "Bandit ",
        "Bear ",
        "Bone- ",
        "Brain- ",
        "Breeding ",
        "Bronze ",
        "Centipede- ",
        "Clan of the ",
        "Cloned ",
        "Cloud- ",
        "Conjoined ",
        "Crocodile- ",
        "Cursed ",
        "Dark ",
        "Decayed ",
        "Deceitful ",
        "Demonic ",
        "Deranged ",
        "Diseased ",
        "Elemental ",
        "Enchanted ",
        "Enslaved ",
        "Feral ",
        "Flame- ",
        "Flying ",
        "Forest ",
        "Frost ",
        "Genius ",
        "Giant ",
        "Grotesque ",
        "Guardian ",
        "Half-breed ",
        "Hallucinogenic ",
        "Hellish ",
        "Horde of the ",
        "Horned ",
        "Horrific ",
        "Howling ",
        "Hybrid ",
        "Ice ",
        "Imprisoned ",
        "Insane ",
        "Insidious ",
        "Iron ",
        "Iron ",
        "Jade ",
        "Lava ",
        "Leeching ",
        "Leopard- ",
        "Lunar ",
        "Mad ",
        "Mammoth ",
        "Many-legged ",
        "Massive ",
        "Master ",
        "Mastermind ",
        "Mechanical ",
        "Mental ",
        "Mind ",
        "Minions of the ",
        "Mist- ",
        "Monkey- ",
        "Moon- ",
        "Moth- ",
        "Mutant ",
        "Narcotic ",
        "Poisonous ",
        "Polluted ",
        "Predatory ",
        "Raider- ",
        "Reaver ",
        "Reawakened ",
        "Resurrected ",
        "Sabertoothed ",
        "Sand- ",
        "Scarlet ",
        "Scheming ",
        "Sea- ",
        "Shadow ",
        "Skeletal ",
        "Slime- ",
        "Slug- ",
        "Smoke ",
        "Snail- ",
        "Snake- ",
        "Spell- ",
        "Summoned ",
        "Tribe of the ",
        "Undead ",
        "Unholy ",
        "Vampiric ",
        "Villainous ",
        "Water ",
        "Winged ",
        "Wounded ",
        "Wraith- "
      ]];

      const secondFeature = [[
        "Abbot",
        "Actor",
        "Alchemist",
        "Altar",
        "Apparition",
        "Apprentice",
        "Assassin",
        "Beast",
        "Behemoth",
        "Binder",
        "Bishop",
        "Breeder",
        "Brood",
        "Brotherhood",
        "Burrower",
        "Caller",
        "Captive",
        "Ceremony",
        "Chalice",
        "Changeling",
        "Chanter",
        "Circlet",
        "Clan",
        "Collector",
        "Combiner",
        "Congregation",
        "Coronet",
        "Crafter",
        "Crawler",
        "Creator",
        "Creature",
        "Crown",
        "Cult",
        "Cultists",
        "Daughter",
        "Demon",
        "Device",
        "Dreamer",
        "Druid",
        "Egg",
        "Emissary",
        "Half-breed Emperor",
        "Executioner",
        "Exile",
        "Experimenter",
        "Eye",
        "Father",
        "Gatherer",
        "God",
        "Goddess",
        "Golem",
        "Grail",
        "Guardian",
        "Head",
        "Horde",
        "Hunter",
        "Hunters",
        "Hybrid",
        "Idol",
        "Jailer",
        "Keeper",
        "Killer",
        "King",
        "Knight",
        "Lich",
        "Lord",
        "Mage",
        "Magician",
        "Man-eating Maker",
        "Master",
        "Many-legged Monks",
        "Mother",
        "People",
        "Priest",
        "Priesthood",
        "Prince",
        "Princess",
        "Puppet",
        "Reaver",
        "Resurrectionist",
        "Scholar",
        "Seed",
        "Shaper",
        "Sisterhood",
        "Slitherer",
        "Society",
        "Son",
        "Sorcerer",
        "Sorceress",
        "Spawn",
        "Star",
        "Statue",
        "Surgeon",
        "Tree",
        "Tribe",
        "Walker",
        "Warlord",
        "Weaver",
        "Whisperer",
        "Wizard"
      ], [
        "Artifact",
        "Assassin",
        "Automaton",
        "Basilisk",
        "Bat(s)",
        "Beast",
        "Behemoth",
        "Berserker(s)",
        "Cannibal",
        "Centaur",
        "Chieftain of Goblins",
        "Chimera",
        "Cleric",
        "Cockatrice",
        "Colossus",
        "Creature",
        "Cyclops",
        "Demigod",
        "Demon",
        "Displacer",
        "Djinni",
        "Doppelganger",
        "Dragon",
        "Druid",
        "Efreet",
        "Eyeball",
        "Frog",
        "Fungus",
        "Gargoyle(s)",
        "Genie",
        "Ghost(s)",
        "Ghouls",
        "Giant(s)",
        "God",
        "Golem",
        "Griffon",
        "Hag",
        "Harpies",
        "Hornet(s)",
        "Horror",
        "Hound(s)",
        "Hydra",
        "Idol",
        "Infiltrator",
        "Insect",
        "Larva",
        "Lich",
        "Lycanthrope",
        "Mage",
        "Magician",
        "Manticore",
        "Master",
        "Medusa",
        "Minotaur(s)",
        "Monster",
        "Mummy",
        "Mushroom",
        "Naga",
        "Nomads",
        "Octopus",
        "Ogre(s)",
        "Ooze(s)",
        "Pirate(s)",
        "Priest(s)",
        "Princess",
        "Pudding(s)",
        "Puppet",
        "Rakshasa",
        "Rat(s)",
        "Salamander",
        "Satyr",
        "Scorpion",
        "Serpent",
        "Shaman",
        "Shaman of the Orcs",
        "Simulacrum",
        "Skeletons",
        "Slime(s)",
        "Spawn",
        "Sphinx",
        "Spider(s)",
        "Spirits",
        "Statue",
        "Titan",
        "Toad",
        "Tree",
        "Troglodytes",
        "Troll(s)",
        "Tyrant",
        "Warlord of the Orcs",
        "Wasp(s)",
        "Witch",
        "Wizard",
        "Wolves",
        "Worg(s)",
        "Worm",
        "Wyrm",
        "Wyvern",
        "Yeti",
        "Zombies"
      ]];

      function getRandomListItem(list) {
        return list[Math.floor(Math.random()*list.length)];
      };

      function assembleOverviewString(index) {
        return getRandomListItem(structureDescription[index]) + " " + getRandomListItem(structure[index]) + getRandomListItem(firstFeature[index]) + getRandomListItem(secondFeature[index]);
      }

      function appendListItem(text) {
        var mainContainer = document.getElementById("overviewList");
        var newListItem = document.createElement('li');
        newListItem.innerHTML = text;
        mainContainer.appendChild(newListItem);
      };     
      
      function destroyListItems() {
        var mainContainer = document.getElementById("overviewList");

        while (mainContainer.firstChild) {
          mainContainer.removeChild(mainContainer.lastChild);
        }
      }

      function generateOverviews() {
        let d2Result = 0;
        destroyListItems();

        for(let idx = 0; idx <= 10; idx++) {
          d2Result = Math.floor(Math.random() * 2);
          console.log(d2Result);
          appendListItem(assembleOverviewString(d2Result));
        }
      };

     

     